
server:
  port: 8080

spring:
  application:
    name: workflow-engine

logging:
  level:
    com.example: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
